application: vjeantetblog
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /(.+)/
  static_files: \1/index.html
  upload: (.+)/index.html

- url: /(.+)
  static_files: \1
  upload: (.*)

- url: /
  static_files: index.html
  upload: index.html


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?