baseurl = "https://www.cloudaid.dk/"
copyright = "All rights reserved"
disqusshortname = ""
languagecode = "en-us"
paginate = 5
pluralizelisttitles = false
theme = "hugo-theme-casper"
title = "cloud aid aps"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/#content"
weight = -120

[params]
  description = "Cloud Projects by Michael Mardahl"
  metadescription = "Cloud projects by Michael Mardahl"
  cover = "images/cover.png"
  author = "Michael Mardahl"
  authorlocation = "Ballerup, Denmark"
  authorwebsite = "https://www.iphase.dk"
  authorbio = "Cloud Enabler - Microsoft Certified Professional"
  logo = "images/logo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = ""
  twitterName = ""
  linkedinName = "cloudaid"
  # facebookName = ""
  # codepenName = ""
  # linkedinName = ""
  # stackoverflowId = ""
  # keybaseName = ""
  # flickrName = ""
  instagramName = ""
  email = "hello@cloudaid.dk"
  # pinterestName = ""
  # googlePlusName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  customFooterPartial = "netlify.html"
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = ""

  #Favicon for all devices, set fav to your favicon,ico to enable, or comment out to disable.
  #Create pack at https://realfavicongenerator.net/ and put in root of static folder.
  favHtml = "favicon.html"
  fav = "favicon.ico"
  favApple = "apple-touch-icon.png"
  fav32 = "favicon-32x32.png"
  fav16 = "favicon-16x16.png"
  favManifest = "site.webmanifest"
  favSafari = "safari-pinned-tab.svg"
  favSafariColor = "#e0a200"
  favTileColor = "#ffc40d"
  favThemeColor = "#ffffff"
  
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
